name: AutoMerge

on:
  check_run:
    types: [completed]

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
    - name: show context
      run: echo "${{ github }}"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
