name: AutoMerge

on:
  - pull_request

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
    - name: 'Run JS'
      uses: dkarter/automerge-workflow@setup-workflow
      with:
        who-to-greet: 'Mona the Octocat'
