name: AutoMerge

on:
  - pull_request

jobs:
  check-merge:
    runs-on: ubuntu-latest

    steps:
    - name: 'Run JS'
      uses: dkarter/automerge-workflow@setup-workflow
      with:
        mergeLabel: 'Ready To Merge'
        shouldUpdateBranch: true
        repoToken: "${{ secrets.GITHUB_TOKEN }}"

